export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';

export const GET_DEPARTMENTS_START = 'GET_DEPARTMENTS_START';
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENTS_FAIL = 'GET_DEPARTMENTS_FAIL';

export const GET_CATEGORY_IN_DEPARTMENT_START = 'GET_CATEGORY_IN_DEPARTMENT_START';
export const GET_CATEGORY_IN_DEPARTMENT_SUCCESS = 'GET_CATEGORY_IN_DEPARTMENT_SUCCESS';
export const GET_CATEGORY_IN_DEPARTMENT_FAIL = 'GET_CATEGORY_IN_DEPARTMENT_FAIL';

export const GET_PRODUCT_IN_DEPARTMENT_START = 'GET_PRODUCT_IN_DEPARTMENT_START';
export const GET_PRODUCT_IN_DEPARTMENT_SUCCESS = 'GET_PRODUCT_IN_DEPARTMENT_SUCCESS';
export const GET_PRODUCT_IN_DEPARTMENT_FAIL = 'GET_PRODUCT_IN_DEPARTMENT_FAIL';

export const GET_PRODUCT_IN_CATEGORY_START = 'GET_PRODUCT_IN_CATEGORY_START';
export const GET_PRODUCT_IN_CATEGORY_SUCCESS = 'GET_PRODUCT_IN_CATEGORY_SUCCESS';
export const GET_PRODUCT_IN_CATEGORY_FAIL = 'GET_PRODUCT_IN_CATEGORY_FAIL';

export const GET_PRODUCT_DETAILS_START = 'GET_PRODUCT_DETAILS_START';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';

export const GET_ATTRIBUTES_IN_PRODUCT_START = 'GET_ATTRIBUTES_IN_PRODUCT_START';
export const GET_ATTRIBUTES_IN_PRODUCT_SUCCESS = 'GET_ATTRIBUTES_IN_PRODUCT_SUCCESS';
export const GET_ATTRIBUTES_IN_PRODUCT_FAIL = 'GET_ATTRIBUTES_IN_PRODUCT_FAIL';

export const GENERATE_UNIQUE_CART_ID_START = 'GENERATE_UNIQUE_CART_ID_START';
export const GENERATE_UNIQUE_CART_ID_SUCCESS = 'GENERATE_UNIQUE_CART_ID_SUCCESS';
export const GENERATE_UNIQUE_CART_ID_FAIL = 'GENERATE_UNIQUE_CART_ID_FAIL';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const UPDATE_CART_START = 'UPDATE_CART_START';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL';
