export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';

export const GET_DEPARTMENTS_START = 'GET_DEPARTMENTS_START';
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENTS_FAIL = 'GET_DEPARTMENTS_FAIL';

export const GET_CATEGORY_IN_DEPARTMENT_START = 'GET_CATEGORY_IN_DEPARTMENT_START';
export const GET_CATEGORY_IN_DEPARTMENT_SUCCESS = 'GET_CATEGORY_IN_DEPARTMENT_SUCCESS';
export const GET_CATEGORY_IN_DEPARTMENT_FAIL = 'GET_CATEGORY_IN_DEPARTMENT_FAIL';

export const GET_PRODUCT_IN_DEPARTMENT_START = 'GET_PRODUCT_IN_DEPARTMENT_START';
export const GET_PRODUCT_IN_DEPARTMENT_SUCCESS = 'GET_PRODUCT_IN_DEPARTMENT_SUCCESS';
export const GET_PRODUCT_IN_DEPARTMENT_FAIL = 'GET_PRODUCT_IN_DEPARTMENT_FAIL';

export const GET_PRODUCT_IN_CATEGORY_START = 'GET_PRODUCT_IN_CATEGORY_START';
export const GET_PRODUCT_IN_CATEGORY_SUCCESS = 'GET_PRODUCT_IN_CATEGORY_SUCCESS';
export const GET_PRODUCT_IN_CATEGORY_FAIL = 'GET_PRODUCT_IN_CATEGORY_FAIL';

export const GET_PRODUCT_DETAILS_START = 'GET_PRODUCT_DETAILS_START';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';

export const GET_ATTRIBUTES_IN_PRODUCT_START = 'GET_ATTRIBUTES_IN_PRODUCT_START';
export const GET_ATTRIBUTES_IN_PRODUCT_SUCCESS = 'GET_ATTRIBUTES_IN_PRODUCT_SUCCESS';
export const GET_ATTRIBUTES_IN_PRODUCT_FAIL = 'GET_ATTRIBUTES_IN_PRODUCT_FAIL';

export const GENERATE_UNIQUE_CART_ID_START = 'GENERATE_UNIQUE_CART_ID_START';
export const GENERATE_UNIQUE_CART_ID_SUCCESS = 'GENERATE_UNIQUE_CART_ID_SUCCESS';
export const GENERATE_UNIQUE_CART_ID_FAIL = 'GENERATE_UNIQUE_CART_ID_FAIL';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const UPDATE_CART_START = 'UPDATE_CART_START';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL';

export const GET_PRODUCT_IN_CART_START = 'GET_PRODUCT_IN_CART_START';
export const GET_PRODUCT_IN_CART_SUCCESS = 'GET_PRODUCT_IN_CART_SUCCESS';
export const GET_PRODUCT_IN_CART_FAIL = 'GET_PRODUCT_IN_CART_FAIL';

export const REMOVE_PRODUCT_IN_CART_START = 'REMOVE_PRODUCT_IN_CART_START';
export const REMOVE_PRODUCT_IN_CART_SUCCESS = 'REMOVE_PRODUCT_IN_CART_SUCCESS';
export const REMOVE_PRODUCT_IN_CART_FAIL = 'REMOVE_PRODUCT_IN_CART_FAIL';

export const GET_TOTAL_AMOUNT_IN_CART_START = 'GET_TOTAL_AMOUNT_IN_CART_START';
export const GET_TOTAL_AMOUNT_IN_CART_SUCCESS = 'GET_TOTAL_AMOUNT_IN_CART_SUCCESS';
export const GET_TOTAL_AMOUNT_IN_CART_FAIL = 'GET_TOTAL_AMOUNT_IN_CART_FAIL';

export const REGISTER_CUSTOMER_START = 'REGISTER_CUSTOMER_START';
export const REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS';
export const REGISTER_CUSTOMER_FAIL = 'REGISTER_CUSTOMER_FAIL';

export const LOGIN_CUSTOMER_START = 'LOGIN_CUSTOMER_START';
export const LOGIN_CUSTOMER_SUCCESS = 'LOGIN_CUSTOMER_SUCCESS';
export const LOGIN_CUSTOMER_FAIL = 'LOGIN_CUSTOMER_FAIL';

export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER';

export const GET_SHIPPING_REGION_START = 'GET_SHIPPING_REGION_START';
export const GET_SHIPPING_REGION_SUCCESS = 'GET_SHIPPING_REGION_SUCCESS';
export const GET_SHIPPING_REGION_FAIL = 'GET_SHIPPING_REGION_FAIL';

export const GET_SHIPPING_REGION_WITH_COST_START = 'GET_SHIPPING_REGION_WITH_COST_START';
export const GET_SHIPPING_REGION_WITH_COST_SUCCESS = 'GET_SHIPPING_REGION_WITH_COST_SUCCESS';
export const GET_SHIPPING_REGION_WITH_COST_FAIL = 'GET_SHIPPING_REGION_WITH_COST_FAIL';

export const UPDATE_CUSTOMER_ADDRESS_START = 'UPDATE_CUSTOMER_ADDRESS_START';
export const UPDATE_CUSTOMER_ADDRESS_SUCCESS = 'UPDATE_CUSTOMER_ADDRESS_SUCCESS';
export const UPDATE_CUSTOMER_ADDRESS_FAIL = 'UPDATE_CUSTOMER_ADDRESS_FAIL';

export const ORDER_PRODUCT_START = 'ORDER_PRODUCT_START';
export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
export const ORDER_PRODUCT_FAIL = 'ORDER_PRODUCT_FAIL';

export const CHARGE_CUSTOMER_START = 'CHARGE_CUSTOMER_START';
export const CHARGE_CUSTOMER_SUCCESS = 'CHARGE_CUSTOMER_SUCCESS';
export const CHARGE_CUSTOMER_FAIL = 'CHARGE_CUSTOMER_FAIL';
